root: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
rules:
  "no-unused-vars": "error"
  "semi": ["error", "never"]
